### ISSUE TITLE
GitHub Actions: mlcのCIが実行前に強制停止している

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#3804]
## WHY

- Gitの脆弱性対策のため、

 See:
https://github.blog/2022-04-12-git-security-vulnerability-announced/

## WHAT

- エラーメッセージに書かれていた内容をCIに追加をしたが、反映されていない

git config --global --add safe.directory /github/workspace

```yml
name: Check Markdown links for modified files

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Set safe.directory in Git
      run: |
        # HACK:
        # This solution may not be good.

        # See:
        # https://github.blog/2022-04-12-git-security-vulnerability-announced/
        # https://github.com/actions/checkout/blob/main/README.md#push-a-commit-using-the-built-in-token
        git --version
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config --global --add safe.directory /github/workspace
        git config --global -l

    - name: Run markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        check-modified-files-only: 'yes'
```
