### ISSUE TITLE
GitHub Actions: mlcで差分をチェックするときに、ツイートが閲覧できてもNot Foundと判定されてしまう

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#3821]
- repo全体をチェックするworkflowでは、全てpassしている
- この違いは何か?

**Comment by KATO-Hiro** [comment]
#3838 で本家のv1を利用するようにしたが変わらず

**Comment by KATO-Hiro** [comment]
```yml
  "httpHeaders": [
    {
      "urls": ["https://docs.github.com/"],
      "headers": {
        "Accept-Encoding": "zstd, br, gzip, deflate"
      }
    }
  ]
```
