### ISSUE TITLE
masterブランチにpushされたときだけActionsを回す

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#46]

**Comment by KATO-Hiro** [comment]
GitHub Actionのドキュメント通りに記述したのに、シンタックスエラーの扱いになる。
現時点では、原因の特定ができず。

```yml
# OK
on: push
...

# NG
on:
  push:
    - master                 
```
