### ISSUE TITLE
UI: 夜間モードのヘッダーが指定した色からデフォルト色になっているので元に戻す

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderClans#6336]

**Comment by KATO-Hiro** [comment]
```css
[data-md-color-scheme="foo"] {
  --md-primary-fg-color:        #159957;
  --md-default-bg-color: #2E303E;
}

```
